DROP DATABASE IF EXISTS leo;
CREATE DATABASE leo;

use leo;

DROP TABLE IF EXISTS entry;
CREATE TABLE entry (
  id INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  asin VARCHAR(20) NOT NULL,
  thumb VARCHAR(1000) DEFAULT '',
  url VARCHAR(100) NOT NULL,
  store VARCHAR(100) NOT NULL,
  status TINYINT(1) DEFAULT 0,
  error TINYINT(3) DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT '2016-10-18',
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS log;
CREATE TABLE log (
  id INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  entry_id INT(20) UNSIGNED NOT NULL,
  cache VARCHAR(100) NOT NULL,
  rank INT(10) UNSIGNED NOT NULL DEFAULT 0,
  sub_rank INT(10) UNSIGNED NOT NULL DEFAULT 0,
  total_review INT(10) UNSIGNED NOT NULL DEFAULT 0,
  average_star FLOAT NOT NULL DEFAULT 0.0,
  star_1 FLOAT NOT NULL DEFAULT 0.0,
  star_2 FLOAT NOT NULL DEFAULT 0.0,
  star_3 FLOAT NOT NULL DEFAULT 0.0,
  star_4 FLOAT NOT NULL DEFAULT 0.0,
  star_5 FLOAT NOT NULL DEFAULT 0.0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS order_info;
CREATE TABLE order_info (
  id INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id VARCHAR(50) DEFAULT '',
  customer_id VARCHAR(50) DEFAULT '',
  asin VARCHAR(50) DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE INDEX (order_id)
);
